name: Run testRigor Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run testRigor tests
        uses: testRigor/actions@v1
        with:
          test_suite_id: ${{ secrets.TESTRIGOR_SUITE_ID }}
          api_token: ${{ secrets.TESTRIGOR_API_TOKEN }}
